version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
    COMPOSE_DOCKER_CLI_BUILD: "1"

phases:
  install:
    commands:
      - echo "=== Phase 1: Installing dependencies ==="
      - curl -SL "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - docker-compose --version

  pre_build:
    commands:
      - echo "=== Phase 2: Validating configuration ==="
      - docker-compose config > /dev/null
      - echo "Configuration is valid"

  build:
    commands:
      - echo "=== Phase 3: Building and testing ==="
      - echo "Step 1 - Building Docker images..."
      - docker-compose build --no-cache
      - echo "Step 2 - Starting application stack..."
      - docker-compose up -d
      - echo "Step 3 - Waiting for services to be healthy..."
      - sleep 15
      - docker-compose ps
      - echo "Step 4 - Running E2E tests with coverage..."
      - docker run --rm --network docker-hooks-mcp_test-network -e API_URL=http://api:3000 -v "$(pwd)/tests:/tests" -w /tests node:20-alpine sh -c "npm ci && npm run test:ci"
      - echo "Tests completed successfully"

  post_build:
    commands:
      - echo "=== Phase 4: Cleanup ==="
      - docker-compose down -v || true
      - echo "Cleanup completed"

reports:
  e2e-test-reports:
    files:
      - "tests/junit.xml"
    file-format: JUNITXML
  coverage-reports:
    files:
      - "tests/coverage/clover.xml"
    file-format: CLOVERXML
