version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
    COMPOSE_DOCKER_CLI_BUILD: "1"

phases:
  install:
    commands:
      - echo "Installing docker-compose"
      - curl -SL "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - docker-compose --version

  pre_build:
    commands:
      - echo "Validating docker-compose.yml"
      - docker-compose config > /dev/null
      - echo "Validation passed"

  build:
    commands:
      - echo "Building Docker images"
      - docker-compose build --no-cache
      - echo "Starting test stack"
      - docker-compose up -d
      - echo "Waiting for services"
      - sleep 15
      - docker-compose ps
      - echo "Running E2E tests"
      - docker run --rm --network docker-hooks-mcp_test-network -e API_URL=http://api:3000 -v "$(pwd)/tests:/tests" -w /tests node:20-alpine sh -c "npm ci && npm run test:ci"
      - echo "E2E tests completed"

  post_build:
    commands:
      - echo "Cleanup - stopping containers"
      - docker-compose down -v || true
      - echo "Build completed"

reports:
  e2e-test-reports:
    files:
      - "tests/junit.xml"
    file-format: JUNITXML
